name: Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          sudo apt install -y chromium-chromedriver

      - name: Run Selenium Tests
        run: pytest --tb=short --maxfail=5 --html=report.html --self-contained-html || true

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: selenium-test-report
          path: report.html
